# RAW is sacred: landed source data that cannot be regenerated by rerunning code.
# PROD is disposable: everything in it is rebuilt from RAW + Git by dbt.
# That distinction is what drives retention, the destroy guard, and the migration plan.

resource "snowflake_database" "raw" {
  name                        = "RAW"
  comment                     = "Landed source data. Written by ingestion only; dbt reads via source()."
  data_retention_time_in_days = 7

  lifecycle {
    prevent_destroy = true
  }
}

resource "snowflake_database" "prod" {
  name    = "PROD"
  comment = "dbt-built tables. Fully reproducible from RAW + Git."
}

resource "snowflake_schema" "raw_metering" {
  database = snowflake_database.raw.name
  name     = "METERING"
  comment  = "Smart meter readings. Personal data under GDPR."

  lifecycle {
    prevent_destroy = true
  }
}
