terraform {
  required_version = ">= 1.5"

  required_providers {
    snowflake = {
      source  = "snowflakedb/snowflake"
      version = "~> 2.19"
    }
  }
}

# Credentials come from SNOWFLAKE_* environment variables — see .env.example.
provider "snowflake" {}

# --- Databases -------------------------------------------------------------
# RAW is sacred: landed source data that cannot be regenerated by rerunning
# code. PROD is disposable: rebuilt from RAW + Git by dbt. That distinction
# drives retention, the destroy guard, and the migration plan.

resource "snowflake_database" "raw" {
  name                        = "RAW"
  comment                     = "Landed source data. Written by ingestion only; dbt reads via source()."
  data_retention_time_in_days = 7

  lifecycle {
    prevent_destroy = true
  }
}

resource "snowflake_database" "prod" {
  name    = "PROD"
  comment = "dbt-built tables. Fully reproducible from RAW + Git."
}

resource "snowflake_schema" "raw_metering" {
  database = snowflake_database.raw.name
  name     = "METERING"
  comment  = "Smart meter readings. Personal data under GDPR."

  lifecycle {
    prevent_destroy = true
  }
}

# --- Compute ---------------------------------------------------------------
# XS by default with a short auto-suspend. Heavy models get routed to a bigger
# warehouse per-model via dbt's snowflake_warehouse config, rather than sizing
# this one up for everyone.

resource "snowflake_warehouse" "transforming" {
  name           = "TRANSFORMING_WH"
  warehouse_size = "XSMALL"
  auto_suspend   = 60
  auto_resume    = true
  comment        = "dbt transformations."
}

# --- Access ----------------------------------------------------------------
# One functional role for now: the identity dbt runs as. Team roles
# (finance_analyst, grid_engineer, ...) come next, granted via access roles.

resource "snowflake_account_role" "transformer" {
  name    = "TRANSFORMER"
  comment = "Identity dbt runs as. Reads RAW, owns everything in PROD."
}

resource "snowflake_grant_privileges_to_account_role" "transformer_warehouse" {
  account_role_name = snowflake_account_role.transformer.name
  privileges        = ["USAGE"]

  on_account_object {
    object_type = "WAREHOUSE"
    object_name = snowflake_warehouse.transforming.name
  }
}

resource "snowflake_grant_privileges_to_account_role" "transformer_raw_database" {
  account_role_name = snowflake_account_role.transformer.name
  privileges        = ["USAGE"]

  on_account_object {
    object_type = "DATABASE"
    object_name = snowflake_database.raw.name
  }
}

resource "snowflake_grant_privileges_to_account_role" "transformer_raw_schema" {
  account_role_name = snowflake_account_role.transformer.name
  privileges        = ["USAGE"]

  on_schema {
    schema_name = snowflake_schema.raw_metering.fully_qualified_name
  }
}

# Read-only on RAW, existing tables and future ones. dbt must never write
# here — RAW belongs to ingestion.
resource "snowflake_grant_privileges_to_account_role" "transformer_raw_tables" {
  account_role_name = snowflake_account_role.transformer.name
  privileges        = ["SELECT"]

  on_schema_object {
    all {
      object_type_plural = "TABLES"
      in_schema          = snowflake_schema.raw_metering.fully_qualified_name
    }
  }
}

resource "snowflake_grant_privileges_to_account_role" "transformer_raw_future_tables" {
  account_role_name = snowflake_account_role.transformer.name
  privileges        = ["SELECT"]

  on_schema_object {
    future {
      object_type_plural = "TABLES"
      in_database        = snowflake_database.raw.name
    }
  }
}

# PROD is dbt's to build in: it creates its own schemas and tables there.
resource "snowflake_grant_privileges_to_account_role" "transformer_prod" {
  account_role_name = snowflake_account_role.transformer.name
  privileges        = ["USAGE", "CREATE SCHEMA"]

  on_account_object {
    object_type = "DATABASE"
    object_name = snowflake_database.prod.name
  }
}

# Named directly rather than via a variable: it is an identity, not a secret,
# and there is exactly one correct value until a service user replaces it.
resource "snowflake_grant_account_role" "transformer_to_dbt_user" {
  role_name = snowflake_account_role.transformer.name
  user_name = "MATHIASO3110"
}
